# Generated by Django 4.2 on 2023-06-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='precout',
            new_name='precaution',
        ),
    ]
